### ISSUE TITLE
Create profile Component

### ISSUE THREAD

**Issue by stojanov-igor** [UniversalDot/universal-dot-front-end#2]
Create a basic React Component based on UI Design

The User should have Profile Information such as:

- [x] Account ID
- [x] Interests (String)
- [x] Reputation
- [x] Balance

**Comment by stojanov-igor** [comment]
Comment regarding initial findings on how data is pulled from the back-end. 

navigate to src/substrate-lib
Check index.js within that path.
You can see that ContextProvider is being injected
Go TO substrateContext within the same folder
You can see how data is being passed via WebSocket 
`const connect = (state, dispatch) => {
const { apiState, socket, jsonrpc } = state;`

**Comment by stojanov-igor** [comment]
The JS API documentation is available here: https://polkadot.js.org/docs/ 

@slaveatanasov. Please read these documents to get more info on the data coming from Rust: 

1. https://polkadot.js.org/docs/api/start/basics
2. https://polkadot.js.org/docs/api/start/api.rpc
3. https://polkadot.js.org/docs/api/start/keyring
4. https://polkadot.js.org/docs/api/start/types.basics

The documentation is pretty good.. so check it out.

**Comment by stojanov-igor** [comment]
The also expose Typescript types via API: https://polkadot.js.org/docs/api/start/typescript

**Comment by slaveatanasov** [comment]
Things to clarify:

- API response status codes, names, and order (which code to use to update UI)
- Use JSON structure for sending and receiving data from the BE; all transformations to be done on the BE;

**Comment by stojanov-igor** [comment]
Some general information you must know... 

Substrate JS API

One of the most important things to understand about the @polkadot/api is that most interfaces are actually generated automatically when it connects to a running node. This is quite a departure from other APIs in projects where the interfaces are static. While sounding quite scary, it actually is a powerful concept that exists in both Polkadot and Substrate chains, and allows the API to be used in environments where the chain is customized.

When the API connects to a node, one of the first things it does is to retrieve the metadata and decorate the API based on the metadata information. The metadata effectively provides data in the form of api.<type>.<module>.<section> that fits into one of the following categories -
* consts - All runtime constants, e.g. api.consts.balances.existentialDeposit. These are not functions, rather accessing the endpoint immediately yields the result as defined.
* query - All chain state, e.g. api.query.system.account(<accountId>).
* tx - All extrinsics, e.g. api.tx.balances.transfer(<accountId>, <value>).
Additionally the metadata also provides information on events, these are query-able via the api.query.system.events() interface and also appear on transactions... both these cases are detailed later.

The metadata defines the calls with all the type names used in the various interfaces. At the moment (this is undergoing investigations and could improve in future versions of metadata), this also means that the types between the API and the node need to be aligned. For instance, by default Substrate defines a BlockNumber type as a u32 and the API follows the Substrate defaults - if a chain has a different definitions, the API needs to be aware of this so it can actually decode (and encode) the type.

Types

 Everything returned by the API is a type and has a consistent interface: Codec. This means that a Vec<u32> (an array of u32 values) as well as a Struct (an pre-defined object) or an Enum has the same consistent base interface. Specific types will have values, based on the type - decorated and available.
As a minimum, anything returned by the API, be it a Vec<...>, Option<...>, Struct or any normal type will always have the following methods - as defined on the Codec interface:
* .eq(<other value>) - checks for equality against the other value. In all cases, it will accept "like" values, i.e. in the case of a number you can pass a primitive (such as 1), a hex value (such as 0x01) or even an Unit8Array
* toHex() - returns a hex-base representation of the value, always prefixed by 0x
* toHuman() - returns Human-parsable JSON structure with values formatted as per the settings
* toJSON() - returns a JSON-like representation of the value, this is generally used when calling JSON.stringify(...) on the value
* toString() - returns a string representation, in some cases this performs additional encoding, i.e. for Address, AccountId and AccountIndex it will encode to the ss58 address
* .toU8a() - returns a Uint8Array representation of the encoded value (generally exactly as passed to the node, where values are SCALE encoded)

There is a Typescript definition generator tool that we can use to generate our type definitions for the API: https://polkadot.js.org/docs/api/examples/promise/typegen/ 

I have create a branch where we can extract the types: https://github.com/UniversalDot/universal-dot-front-end/tree/feat/types-definition

**Comment by stojanov-igor** [comment]
Profile component created. Closing this issue.
