### ISSUE TITLE
Create Task Component

### ISSUE THREAD

**Issue by stojanov-igor** [UniversalDot/universal-dot-front-end#5]

**Comment by slaveatanasov** [comment]
Things to clarify:

- Check if you can pull all tasks in 1 query, instead of doing a separate query for each task;

**Comment by stojanov-igor** [comment]
The API allows for a multi-query approach.

Read this: https://polkadot.js.org/docs/api/start/api.query.multi

**Comment by stojanov-igor** [comment]
Initial UI Task component was created.
